server:
  port: 8802
  
spring:
  application:
    name: service-order
  zipkin:
    base-url: http://peer1:9411
  sleuth:
    sampler:
      percentage: 1
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
  instance:
    prefer-ip-address: true
    status-page-url: http://peer1:${server.port}/swagger-ui.html
    
feign:
  hystrix:
    enabled: true
